// WHAT IS CONSIDERED WHITESPACE
#define WHITESPACE_CHARS " \t~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"

// SET TO ZERO FOR INDENTING WITH TABS
#define DEFAULT_INDENT_SIZE 0
// THE WIDTH OF THE TAB CHARACTER
#define DEFAULT_TAB_WIDTH 8
// WHETHER TO AUTOMATICALLY MAINTAIN THE SAME INDENTATION LEVEL OR NOT
#define DEFAULT_AUTOTAB true



